# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AlanAuckland's blog
email: alanauckland86@gmail.com
description: > # I have created this blog to record the things I learn and care
               about, namley, anything related to I.T or technology. If I can
               entertain, enspire and help others learn faster than this will
               make me a much a better person. I hope you enoy some aspect of
               my future posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alanauckland86.github.io" # the base hostname & protocol for your site
twitter_username: alanauckland86
github_username:  alanauckland86

# Build settings
markdown: kramdown
